# Generated by Django 5.1.15 on 2026-07-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=64, unique=True)),
                ('game_id', models.CharField(blank=True, max_length=128)),
                ('avatar_url', models.URLField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nick'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('bracket_side', models.CharField(choices=[('winners', 'Winners bracket'), ('losers', 'Losers bracket'), ('final', 'Grand final')], default='winners', max_length=8)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['bracket_side', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['seed', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team_size', models.PositiveSmallIntegerField(default=1)),
                ('bracket_type', models.CharField(choices=[('single', 'Single elimination'), ('double', 'Double elimination')], default='single', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Příprava'), ('in_progress', 'Probíhá'), ('completed', 'Dokončeno / archiv')], default='draft', max_length=12)),
                ('seeding_method', models.CharField(choices=[('random', 'Náhodně'), ('rating', 'Podle ratingu (K/D)')], default='random', max_length=10)),
                ('season', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('score_a', models.PositiveIntegerField(default=0)),
                ('score_b', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Čeká'), ('completed', 'Dohráno')], default='pending', max_length=10)),
                ('next_slot', models.CharField(blank=True, choices=[('a', 'Slot A'), ('b', 'Slot B')], max_length=1, null=True)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.match')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.round')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.team')),
            ],
            options={
                'ordering': ['round', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tournaments.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tournaments.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='tournaments.TeamMembership', to='tournaments.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='MatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tournaments.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='tournaments.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('tournament', 'index', 'bracket_side')},
        ),
    ]
