# Generated by Django 5.1.15 on 2026-07-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='loser_next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_next_slot',
            field=models.CharField(blank=True, choices=[('a', 'Slot A'), ('b', 'Slot B')], max_length=1, null=True),
        ),
    ]
