# Generated by Django 5.1.15 on 2026-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_news_match_loser_next_match_match_loser_next_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='seeding_method',
            field=models.CharField(choices=[('random', 'Náhodně'), ('rating', 'Podle ratingu (K/D)'), ('manual', 'Ruční pořadí (drag & drop)')], default='random', max_length=10),
        ),
    ]
