# Generated by Django 5.1.15 on 2026-07-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_seeding_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='saved_teams', to='tournaments.player')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
