# Generated by Django 5.1.15 on 2026-07-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_teamset_teamsetteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedTeam',
        ),
    ]
