# Generated by Django 5.1.15 on 2026-07-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_delete_savedteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('elimination', 'Vyřazovací (pavouk)'), ('league', 'Bodovací (tabulka)')], default='elimination', max_length=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_per_draw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_per_kill',
            field=models.DecimalField(decimal_places=2, default='0.5', max_digits=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_per_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_per_win',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
