# Generated by Django 5.1.15 on 2026-07-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_mode_tournament_points_per_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stream_url',
            field=models.URLField(blank=True),
        ),
    ]
