# Generated by Django 5.1.15 on 2026-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournament_event_date_tournament_prize_pool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='prize_pool',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
